---

- name: copy nginx repo
  template: src=nginx.repo.j2 dest=/etc/yum.repos.d/nginx.repo

- name: install nginx dependance
  yum: name={{ item }} state=latest
  with_items:
    - pcre-devel
    - openssl-devel
    - zlib-devel
    - gcc-c++

- name: install nginx
  yum: name=nginx state=present
  register: nginx_installed

- name: start nginx
  service: name=nginx state=started enabled=yes

- name: copy openssl and nginx source
  unarchive: src={{ item }} dest=/usr/src
  with_items:
    - openssl-1.1.0f.tar.gz
    - nginx-1.12.0.tar.gz

- name: configure nginx source
  shell: >
    {{ configure_parameter }}
  args:
    chdir: /usr/src/nginx-1.12.0
  register: configure_result
  when: nginx_installed|changed

- name: nginx source make && make install
  shell: make && make install
  args:
    chdir: /usr/src/nginx-1.12.0
  when: configure_result|changed and configure_result|succeeded

- name: increase open files
  pam_limits:
    domain: "*"
    limit_type: "-"
    limit_item: nofile
    value: "{{ max_open_files }}"

- name: configure nginx
  template: src={{ item.src }} dest={{ item.dest }}
  with_items:
    - { src: "nginx.conf.j2", dest: "/etc/nginx/nginx.conf" }
    - { src: "default.conf.j2", dest: "/etc/nginx/conf.d/default.conf" }
  notify:
    - restart nginx
