---

- name: create weblogic user
  user: name=weblogic password={{ weblogic_user_passwd }}

- name: uninstall system jdk
  yum: name=java state=absent

- name: create jdk folder
  file: path={{ JAVA_HOME }} state=directory

- name: copy jdk and wls
  copy: src={{ item.src }} dest={{ item.dest }}
  with_items:
    - { src: 'jdk-8u65-linux-x64.tar.gz' , dest: '/usr/src' }
    - { src: 'fmw_12.1.3.0.0_wls.jar', dest: '/usr/src' }
    - { src: 'wls_12.1.3.rsp' , dest: '/usr/src' }
    - { src: 'oraInst.loc' , dest: '/etc' }

- name: unarchive jdk
  unarchive:
    src: /usr/src/jdk-8u65-linux-x64.tar.gz
    dest: "{{ JAVA_HOME }}"
    remote_src: True

- name: edit java environment
  lineinfile:
    path: /home/weblogic/.bash_profile
    line: "{{ item }}"
  with_items:
    - '# JDK environment'
    - 'JAVA_HOME={{ JAVA_HOME }}'
    - 'JRE_HOME={{ JRE_HOME }}'
    - 'PATH=$PATH:$JAVA_HOME/bin:$JRE_HOME/bin'
    - 'CLASSPATH=.:$JAVA_HOME/lib/dt.jar:$JAVA_HOME/lib/tools.jar:$JRE_HOME/lib'
    - 'export JAVA_HOME JRE_HOME PATH CLASSPATH'

- name: configure silent domain creation
  template: src=basicWLSDomain.py dest=/usr/src

- name: test if wls is installed
  stat: path=/home/weblogic/Oracle/Middleware/Oracle_Home/wlserver
  register: wls_installed

- name: install wls in silent mode
  become: True
  become_user: weblogic
  shell: "{{ JAVA_HOME }}/bin/java -jar fmw_12.1.3.0.0_wls.jar -silent -responseFile /usr/src/wls_12.1.3.rsp -invPtrLoc /etc/oraInst.loc"
  args:
    chdir: /usr/src
  when: wls_installed.stat.exists == False

- name: test if wls is installed
  stat: path=/home/weblogic/Oracle/Middleware/Oracle_Home/user_projects/domains
  register: domain_created

- name: create wls domain with WLST
  become: True
  become_user: weblogic
  shell: bash wlst.sh /usr/src/basicWLSDomain.py
  args:
    chdir: /home/weblogic/Oracle/Middleware/Oracle_Home/wlserver/common/bin
  when: domain_created.stat.exists == False
