---

- name: stop firewall service
  service: name={{ firewall_service }} state=stopped enabled=no

- name: install libselinux-python
  yum: name=libselinux-python state=present

- name: disable selinux
  selinux: state=disabled

- name: stop postfix
  service: name=postfix state=stopped enabled=no

- name: install vmware tool for centos7
  yum: name=open-vm-tools state=latest
  when:
    - ansible_distribution == "CentOS"
    - ansible_distribution_major_version == "7"
    - ansible_product_name == "VMware Virtual Platform"
    
